### ISSUE TITLE
Make package to ease install on Archlinux

### ISSUE THREAD

**Issue by milouse** [srsudar/eg#12]
eg must be easily installable on archlinux, through official repositories or at least on AUR

**Comment by milouse** [comment]
Done https://aur.archlinux.org/packages/eg/ (source are here: http://projects.depar.is/divers/dir?ci=10500f1cb348abe7&name=pkgbuilds/eg)

**Comment by srsudar** [comment]
Awesome, thanks!

So what is now the preferred command to install on archlinux?

**Comment by milouse** [comment]
For now the command is `yaourt -S eg` as the package is only available through non-official user repository AUR (they are very similar to ubuntu's ppa), thus it requires the user to have installed the non-official package manager `yaourt`.

The better way to let the eg's users to know about it is by using the following paragraph for example:

eg is [available](https://aur.archlinux.org/packages/eg/) on Archlinux through the Arch User Repository (AUR). You can install it using yaourt or any [other appropriate tool](https://wiki.archlinux.org/index.php/AUR_helpers):

    yaourt -S eg

**Comment by milouse** [comment]
By the way, the package currently provide the python2 version of  eg, by hard-editing (with sed) the python scripts shebang during installation. I'm following #8 in order to provide a python3 version of eg ASAP, as Archlinux default python interpreter is already the version 3.

**Comment by srsudar** [comment]
Would one of you on archlinux mind seeing if the new release 0.1.0 is pip-installable?

**Comment by milouse** [comment]
What do you want to say with pip-installable? In fact I used to pull from github because (shame on me) I don't look further if you publish stable version elsewhere. Now that I know you push stable version on pipy, I'll use pipy as a source for the package. If I've time and mood for, I'll create a second package, targeted to power user to provide dev version, built from master branch on github (archlinux provide solution to update packages as soon as new commit are pushed somewhere).

**Comment by srsudar** [comment]
Ah I see, sorry. I thought the reason pypi was out was because before this release we didn't support python3. I was just wondering if `pip install eg` works on archlinux now with the latest release.

Your plan sounds like a good one!
