### ISSUE TITLE
weird symbols on terminal

### ISSUE THREAD

**Issue by aminemat** [srsudar/eg#2]
This is what I see when using eg, something I'm missing ?

![selection_006](https://cloud.githubusercontent.com/assets/585335/7299780/975b3628-e99d-11e4-98df-caf79a4f7ca9.png)

**Comment by aminemat** [comment]
Failed to mention my os : Ubuntu 14.10

**Comment by srsudar** [comment]
Are you on windows? The way it colorizes is just ANSI escape sequences, which windows doesn't respect.

Try running `eg --no-color ps`. That will just not including the escape sequences. If that fixes it, I would add the 'color = false' line to your `.egrc`, which will turn that command on by default. See the Color section of [the readme](https://github.com/srsudar/eg) for a complete example.

Hmm you're not on Windows though, eh? Interesting. In that case it looks like for whatever reason the pager isn't respecting color escaping. Hmm. Currently it pages using the `pydoc.pager()` function. Maybe that is using a pager that is preventing color escaping?

Try saving the output to a file with `eg ps >psoutput`. If I edit psoutput with vim, I get the attached screenshot, which is basically what you are seeing. Try looking at that file with `less` and with `cat`. Do you get color for either of those?

![screen shot 2015-04-23 at 8 05 04 am](https://cloud.githubusercontent.com/assets/6362625/7300215/c4fe3aca-e98f-11e4-9239-bf760288481e.png)

**Comment by aminemat** [comment]
So `less  -R outputfile` fixes it, did that after googling http://stackoverflow.com/questions/7922973/python-color-output-and-paging-output
maybe changing the DEFAULT_PAGER will fix it

**Comment by srsudar** [comment]
Awesome. Can you let me know if it fixes it? In the meantime I'll look into issuing the call to `pager` with right flags.

**Comment by aminemat** [comment]
I changed this line and it worked, it broke the tests though, but I'm not a python dev, hope it helps
![selection_007](https://cloud.githubusercontent.com/assets/585335/7301485/8b969db8-e9a8-11e4-8143-8827c2e764d2.png)

**Comment by sgallen** [comment]
I just tried eg and experienced the same issue.  I'm on RHEL 6 (Virtual Box VM, with Win 7 host).  Just wanted to add that `cat` and `less -R` provide the color and `less` the symbols when I tested the output from `eg ps >psoutput`.

**Comment by srsudar** [comment]
Good to know. It looks like `pipepager()` with `cmd='less -R'` works for me as well on OSX. I'll look into the `pydoc` docs to see what intelligent things `pager` tries to do. My thinking with resorting to that method was that it wouldn't be dependent on `less` being installed, but in reality I think most people using it will also have `less`, so that's probably not an issue.

My current thinking is that I'll switch to `cmd='less -R'` and add a `pager_cmd` option to the `egrc` for people to override it if necessary.

**Comment by srsudar** [comment]
I should have a fix for this out by the end of the day, worst case over the weekend.

**Comment by dickiedyce** [comment]
Hi -same issue on a Mac FYI. But great idea!

**Comment by srsudar** [comment]
@dickiedyce Does `less -R` fix it for you as well?

What version of OSX are you using? iTerm or Mac's Terminal app? Bash or zsh? I don't see the problem on Yosemite with zsh.

**Comment by dickiedyce** [comment]
Yep - that's just the ticket. Thanks.

**Comment by dickiedyce** [comment]
bash. zsh is on the todo list ;-)

**Comment by lovek323** [comment]
@srsudar: I see the problem with zsh on Yosemite in iTerm 2. As with others, `less -R` fixes the problem.

**Comment by srsudar** [comment]
Would one of you experiencing the problem mind cloning and trying out the following command on the master branch? `cd` into the root of the repo and then run:

`./eg/eg_exec.py top`

Does it show color as expected?

**Comment by lovek323** [comment]
@srsudar: :+1: Works for me

**Comment by srsudar** [comment]
I just bundled up and released these changes as 0.0.3. Both the current tip and the latest pypi packages should have the fix. (Don't forget you can upgrade using `sudo pip install --upgrade eg`.)

If anybody still sees the issue, please let me know!

**Comment by lovek323** [comment]
Installed, working. Thanks a lot. :smile:

**Comment by sgallen** [comment]
Thanks.  The update works great.

**Comment by aminemat** [comment]
Confirmed working for ubuntu 14.10, thanks

**Comment by srsudar** [comment]
Thanks for the help everybody!
