### ISSUE TITLE
implement `eg egrep` and `eg fgrep`

### ISSUE THREAD

**Issue by cool-RR** [srsudar/eg#29]

**Comment by srsudar** [comment]
What do you think of just aliasing `egrep -> grep`? Regular expressions are covered in `grep`.

I'll add a section to `grep` for `fgrep` as well.

**Comment by srsudar** [comment]
I added the sections as well as aliases for `egrep`, `fgrep`, `zgrep`, `zegrep`, and `zfgrep` to `aliases.json`.
