### ISSUE TITLE
[SOLVED] [TerminalIPythonApp] WARNING | File not found: u'/usr/bin/eg/eg_exec.py'

### ISSUE THREAD

**Issue by pierrepayen** [srsudar/eg#45]
Hi, first, congrats and thanks for this very helpfull program. 
But I have a small problem after installing it with pip on Ubuntu (15.04), I always get this
> payen:~$ sudo pip install eg
>>Downloading/unpacking eg
  Downloading eg-0.1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-Skmbws/eg/setup.py) egg_info for package eg
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
Installing collected packages: eg
  Running setup.py install for eg
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    changing mode of build/scripts-2.7/eg from 644 to 755
    changing mode of /usr/local/bin/eg to 755
Successfully installed eg
Cleaning up...

>payen:~$ eg tar
>>[TerminalIPythonApp] WARNING | File not found: u'/usr/bin/eg/eg_exec.py'

What did I did wrong ?

**Comment by srsudar** [comment]
Hmm that is strange. Did you previously have a manual installation by cloning the git directory? I don't believe that `eg_exec.py` should be showing up otherwise. What is your output from the following commands?

1. `which -a eg`
1. ```less `which eg` ```

**Comment by pierrepayen** [comment]
Thanks, yeah i tried first the manual instalation but i have erased everuthing before installing it with pip.
>payen:~$ which -a eg
>>/usr/local/bin/eg

>payen:~$ less 'which eg'
>>which eg: Aucun fichier ou dossier de ce type

**Comment by srsudar** [comment]
Whoops, backticks not apostrophes. We're just trying to inspect your eg
file. Now that we know where it is, run this:

less /usr/local/bin/eg

What is the output?

**Comment by pierrepayen** [comment]
Look at my previous message :)

**Comment by srsudar** [comment]
Ah great! I was replying via email and it hadn't sent me the updated message. Glad to hear it's working!
