### ISSUE TITLE
Cannot install it on Archlinux with pip

### ISSUE THREAD

**Issue by StatelessCat** [srsudar/eg#6]
The script is runned under python3.4, and fails

**Comment by StatelessCat** [comment]
Just found a workaround:
```sh
mkdir eg-build
cd eg-build
pip2arch -p python2 eg
makepkg
sudo pacman -U eg-*-any.pkg.tar.xz
```

**Comment by srsudar** [comment]
Does it work with python 3.4? I've never tried running it on 3.x.

**Comment by StatelessCat** [comment]
It doesn't :(

**Comment by srsudar** [comment]
Can you open an issue for working with python 3? I should probably bite the bullet and use 3 eventually. If you can give me some error output there that would be awesome as well.

In the meantime, if you have 2.x on your machine as python27 or something like that, you could try altering the `#!` line of `bin/eg` to `#! /path/to/python26` and see if that gets it working for now.

**Comment by StatelessCat** [comment]
Unfortunatly it can't just work to edit the eg ```#!```.
If I edit the ``` #!/usr/bin/python ``` to ``` #!/usr/bin/python2.7 ``` i got : 
```
Traceback (most recent call last):
  File "/usr/bin/eg", line 3, in <module>
    from eg import eg_exec
ImportError: No module named eg
```
I'm not a Python developper, I assume pip, by default on the lastest stable version is doing installation of librairies for python3.x.

I'm not sur if it can help you, but i know many Python devs that are using ```virtualenv``` to handle python version issues like this.

**Comment by srsudar** [comment]
Ah right, right, good point. I'll ruminate on it.

**Comment by StatelessCat** [comment]
:)
