### ISSUE TITLE
missing configuration key in the doc of the egrc

### ISSUE THREAD

**Issue by Sispheor** [srsudar/eg#66]
I would like eg to clean the screen after exit. Currently you use the "X" argument [here ](https://github.com/srsudar/eg/blob/master/eg/config.py#L33)to prevent the cleanup.
I can override the `DEFAULT_PAGER_CMD ` by using [-p PAGER_CMD] but I have to type it everytime.
It would be useful to add this argument to the egrc.

**Comment by Sispheor** [comment]
OK, actually the rc file looks for a var called `pager-cmd`. It's just not documented in the main readme.
You wrote that the rc file can only handle two keys: custom-dir and examples-dir.

**Comment by Sispheor** [comment]
It's actually in the doc.
PEBKAC issue. Sorry :)

**Comment by srsudar** [comment]
Great. The `README` is rather wordy and the info on the config is spread out, so no worries.

Interesting that you want the screen cleared. I like the `X` option so that I can find the example I want and then refer back to it at the prompt.

**Comment by Sispheor** [comment]
Yes, I prefer highlight the command with my mouse to push it in the Linux buffer and then past it into my context. I prefer having a view to last commands.
