### ISSUE TITLE
Emacs wrapper

### ISSUE THREAD

**Issue by mnewt** [srsudar/eg#81]
I created an Emacs wrapper for eg:

https://github.com/mnewt/eg.el

@srsudar Thanks for a great tool and hopefully my addition makes it a little more useful to the Emacs crowd. Of course you can go ahead and close this issue.

Cheers!

**Comment by srsudar** [comment]
Give me vim or give me death!

Just kidding. =) Looks great, thanks for sharing!

The styling you have on the markdown files is also awesome.
