### ISSUE TITLE
Custom pager fails to load in script/function

### ISSUE THREAD

**Issue by Pound-Hash** [srsudar/eg#94]
In the file `~/.config/eg`, I have:

```
[eg-config]
pager-cmd = 'cat'
```

Running `eg less` displays relevant information and returns me to the command line.

In a zsh function, I have:

```
describe_app () {
    if [ "$1" != "" ]; then
        man -f $1;
        eg $1;
        tldr $1;
        cheat $1;
    fi
}
```

Running `describe_app less` displays relevant information, but when eg runs it displays in `less` and does not return to the command line.

**Comment by scorphus** [comment]
Please, make sure you have that content in `${XDG_CONFIG_HOME}/eg/egrc` — which, in most cases, translates to `~/.config/eg/egrc`. [Here's](https://github.com/srsudar/eg#configuration-and-extension) the reference in README.

**Comment by Pound-Hash** [comment]
> Please, make sure you have that content in `${XDG_CONFIG_HOME}/eg/egrc` — which, in most cases, translates to `~/.config/eg/egrc`. [Here's](https://github.com/srsudar/eg#configuration-and-extension) the reference in README.

Yes, that's where I have it. That is,

`~/.config/eg/egrc`

**Comment by Pound-Hash** [comment]
**User error**
The paging by `less` was being called by `cheat`, not `eg`.

**Comment by srsudar** [comment]
Nice. Thanks scorphus for the answer and thanks Pound-Hash for reporting just in case.
